name: Build the game Windows & MaxOsX ğŸ®

on:
  push:
    branches:
      - release
  workflow_dispatch:

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  init-data:
    name: Set the workflow data ğŸ“Š
    runs-on: ubuntu-latest
    outputs:
      builder_number: ${{ steps.builder_number.outputs.build_number }}
    steps:
      - name: Get the number of the current build
        id: builder_number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  buildWindows:
    name: Build the game for Windows ğŸªŸ
    runs-on: ubuntu-latest
    needs: init-data
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get Unity Cache ğŸ—„ï¸
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Build Unity Project for Windows ğŸªŸ
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.42f1
          allowDirtyBuild: true

      - name: Zip the build ğŸ“¦
        uses: montudor/action-zip@v1
        with:
          args: zip qq -r build/build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip build/StandaloneWindows64

      - name: Upload the build ğŸ“¤
        uses: actions/upload-artifact@v3
        with:
          name: build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip
          path: build/StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip

  buildMacOs:
    name: Build the game for MacOsX ğŸ
    runs-on: ubuntu-latest
    needs: init-data
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get Unity Cache ğŸ—„ï¸
        uses: actions/cache@v4
        with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: Library-

      - name: Build Unity Project for MacOsX ğŸ
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          unityVersion: 2022.3.42f1
          allowDirtyBuild: true

      - name: Zip the build ğŸ“¦
        uses: montudor/action-zip@v1
        with:
          args: zip qq -r build/build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip build/StandaloneOSX

      - name: Upload the zip file ğŸ“¤
        uses: actions/upload-artifact@v3
        with:
          name: build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip
          path: build/build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip

  publishAsRelease:
    name: Publish the build as a release ğŸš€
    runs-on: ubuntu-latest
    needs: [buildWindows, buildMacOs, init-data]
    steps:
      - name: Create a release ğŸ“¦
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.init-data.outputs.builder_number }}
          release_name: Release ${{ needs.init-data.outputs.builder_number }}
          draft: false
          prerelease: false
      
      - name: Download the Windows build from the artifact ğŸªŸ
        uses: actions/download-artifact@v2
        with:
          name: build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip

      - name: Upload Windows build ğŸªŸ
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip
          asset_name: build-StandaloneWindows64-${{ needs.init-data.outputs.builder_number }}.zip
          asset_content_type: application/zip

      - name: Download the MacOs build from the artifact ğŸ
        uses: actions/download-artifact@v2
        with:
          name: build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip

      - name: Upload MacOs build ğŸ
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip
          asset_name: build-StandaloneOSX-${{ needs.init-data.outputs.builder_number }}.zip
          asset_content_type: application/zip

      - name: Publish the release ğŸš€
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ needs.init-data.outputs.builder_number }}
          release_name: Release ${{ needs.init-data.outputs.builder_number }}
          draft: false
          prerelease: false
          body: |
            This is the release of the game.
            You can download the game for Windows and MacOsX.
            Enjoy! ğŸ®